### PR TITLE
Add option to mask/hide windows

### PR DESCRIPTION
**Pull request by Dark-Matter7232**
This PR allows the user to mask/hide the windows and access them through window switcher

### CODE REVIEW

**Comment by adi1090x** [comment]
Right... Cool.

**Comment by Dark-Matter7232** [comment]
You need to add a function to build script to manually apply the patch or merge the patch to the rofi source for the upcoming repository

**Comment by Dark-Matter7232** [comment]
You need to add a function to build script to manually apply the patch or
merge the patch to the rofi source for the upcoming repository

**Comment by adi1090x** [comment]
yeah, i'll figure it out.

**Pull request merged**
